baseurl                  = "/"                              # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Introducing Daphne June Sheckells"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
home                     = [ "HTML", "CSS", "RSS" ]
section                  = [ "HTML", "RSS" ]
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "A website created by Lindsay S. Sheckells"
    color                = "ocean"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "oh baby."
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/poppies.mp4"
    type    = "video/mp4"
    poster  = "/background_pop.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "home"
    text = "welcome"

[[params.mainMenu]]
    link = "registry"
    text = "baby registry"

[[params.mainMenu]]
    link = "recommend"
    text = "recommendations"

[[params.mainMenu]]
    link = "shower"
    text = "RSVP for virtual baby shower"

[[params.mainMenu]]
    link = "USpictures"
    text = "ultrasound pictures"

[imaging]
    quality = 75

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
